<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c1e3948f-ab85-4bb8-b3e0-d3e3ae3cd6d5</elementGuidId>
    <imagePath></imagePath>
    <name>link_ProductPromotion</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/main[1]/div[1]/div[1]/div[2]/div[2]/div[4]/div[1]/div[3]/div[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'//tka.tiki.vn/pixel/pixel?data=AVSwi9wdtNmNgbqghJfqMx_uBErqq-eOLAJxwUdtyAt2jYcsnrfpwTaLXiVih1y1S_lRx2Uv_b5DT5MWdN6PVPdT3gs2joy-ZOpP1xHhJJVnhQCCf8B-KbQ1th_I8bFHI0xSKkfXz7tmOqZVps3eKH4S-mwyWvoaYalt2CcSafD0nCwmBj2KJonqQ0TXT0M1F_eniZR21BPeZqqUmWax3NNDrxTtPZZDuIjhjNjips4n2nenClxixCE4j5LiHZWoS9PBhrNKDMem0D-hOuOUtBWPBxl6CXf0xxCURn_wnh37DTI8OP15DziTCeEsw7t2XZoKr3Or-VZy4kHDewaNVenPzwwu6Vi_m7qd5C1tmULYHES-jgAzTDPBbTxyCpwFb9AVpLEUG_5DHmDxH2UQ7XX0tK6RjsSJns7iBPNu_4-A6DyaSf7FlBLyHyutuRC9zlise3_LgIwCRTbKQVxKtXFt3O4AozmbjI5cpQoPj_GmvpVyP2pI9gZo-mhiZai0D77l_pzVxo7D7vAZJ60SM0pvfnylqnuVW4rgx_uKupTFPCFcJaYsniUzCtt7ANMgsGHoRayxQfsC7OJ_fW0SoUqpWImZVQQ4NVJbH5zL_Sam2IAQpzgtaqZqmGNBPeLl0TH0o-RHyK65QtbqYXJQQHjB5SDjkGTdTMleRzzzgdUak_Ne_K5Kt{{aws_access_key}}_dMcb7I1n1LhCHFef-TObHJob73meX0rpTaeY6Z0wWWDRBgzNw9C015Un5ntPquQ9BjJoUgBWMfCBciu0BwR-EK7wf-wOUA_jAM5CZL46qTWazh6EjvreNWQIljIJPDPKg0R7JotFSVZSm1faWrfnFBBqpur_1cR42p5jaGZDaUQJI0NLuUviiVh44Fsq3jverG3Mr9AqR7IDCWnk_GUB8zrEERd5k0dbr23tBV7qjxfAoR2RM3Vhm2I91Orlh4SbFvN96WoEogefhmPrN_X-FlD0amz1ldJTfs3QtuzcaSEhPUYF5fOxkEJtYnDLE8k4v24WCT4XoQXkyPtbBGqhj-eFltJ9T13EBVtgWPdsYXlja_jdAAPrNVltSIZ4pcRQUcteYs6XJKxPegqUrWMCnTo9UzTHTf_cUQ&amp;reqid=qZP4wMqMxfAbB4mH&amp;type=CLICK&amp;pos=3') and equals(@text,'AD
            
            59.000₫
            -50%
            PAKASA
            Bộ tua vít nam châm đa năng 24 đầu PaKaSa - Hàng Chính Hãng
            Đã bán 51
            Giảm 5K
            Giao siêu tốc 2h')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:has-text="AD59.000₫-50%PAKASABộ tua vít"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>//tka.tiki.vn/pixel/pixel?data=AVSwi9wdtNmNgbqghJfqMx_uBErqq-eOLAJxwUdtyAt2jYcsnrfpwTaLXiVih1y1S_lRx2Uv_b5DT5MWdN6PVPdT3gs2joy-ZOpP1xHhJJVnhQCCf8B-KbQ1th_I8bFHI0xSKkfXz7tmOqZVps3eKH4S-mwyWvoaYalt2CcSafD0nCwmBj2KJonqQ0TXT0M1F_eniZR21BPeZqqUmWax3NNDrxTtPZZDuIjhjNjips4n2nenClxixCE4j5LiHZWoS9PBhrNKDMem0D-hOuOUtBWPBxl6CXf0xxCURn_wnh37DTI8OP15DziTCeEsw7t2XZoKr3Or-VZy4kHDewaNVenPzwwu6Vi_m7qd5C1tmULYHES-jgAzTDPBbTxyCpwFb9AVpLEUG_5DHmDxH2UQ7XX0tK6RjsSJns7iBPNu_4-A6DyaSf7FlBLyHyutuRC9zlise3_LgIwCRTbKQVxKtXFt3O4AozmbjI5cpQoPj_GmvpVyP2pI9gZo-mhiZai0D77l_pzVxo7D7vAZJ60SM0pvfnylqnuVW4rgx_uKupTFPCFcJaYsniUzCtt7ANMgsGHoRayxQfsC7OJ_fW0SoUqpWImZVQQ4NVJbH5zL_Sam2IAQpzgtaqZqmGNBPeLl0TH0o-RHyK65QtbqYXJQQHjB5SDjkGTdTMleRzzzgdUak_Ne_K5Kt{{aws_access_key}}_dMcb7I1n1LhCHFef-TObHJob73meX0rpTaeY6Z0wWWDRBgzNw9C015Un5ntPquQ9BjJoUgBWMfCBciu0BwR-EK7wf-wOUA_jAM5CZL46qTWazh6EjvreNWQIljIJPDPKg0R7JotFSVZSm1faWrfnFBBqpur_1cR42p5jaGZDaUQJI0NLuUviiVh44Fsq3jverG3Mr9AqR7IDCWnk_GUB8zrEERd5k0dbr23tBV7qjxfAoR2RM3Vhm2I91Orlh4SbFvN96WoEogefhmPrN_X-FlD0amz1ldJTfs3QtuzcaSEhPUYF5fOxkEJtYnDLE8k4v24WCT4XoQXkyPtbBGqhj-eFltJ9T13EBVtgWPdsYXlja_jdAAPrNVltSIZ4pcRQUcteYs6XJKxPegqUrWMCnTo9UzTHTf_cUQ&amp;reqid=qZP4wMqMxfAbB4mH&amp;type=CLICK&amp;pos=3</value>
        <webElementGuid>4b7de11f-dbb2-4de0-ada8-6c1dd550e181</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>AD
        
        59.000₫
        -50%
        PAKASA
        Bộ tua vít nam châm đa năng 24 đầu PaKaSa - Hàng Chính Hãng
        Đã bán 51
        Giảm 5K
        Giao siêu tốc 2h</value>
        <webElementGuid>4b7de11f-dbb2-4de0-ada8-6c1dd550e181</webElementGuid>
    </webElementProperties>
</WebElementEntity>