<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dacd1aa3-131d-4295-ae75-d8749b8cf43b</elementGuidId>
    <imagePath></imagePath>
    <name>input_VerificationCode3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[10]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[3]/input[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'tel')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Digit 3"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>tel</value>
        <webElementGuid>4b7de11f-dbb2-4de0-ada8-6c1dd550e181</webElementGuid>
    </webElementProperties>
</WebElementEntity>