<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>79869b78-7076-423f-ad6a-a1dcaa91d43b</elementGuidId>
    <imagePath></imagePath>
    <name>link_cartSummary</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/aside[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Go to cart') and equals(@href,'/cart') and equals(@text,'0
            $ 0.00')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>aside &gt;&gt; internal:text="0$"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/cart</value>
        <webElementGuid>0023c2d4-c825-414c-a51d-caf9e5afc445</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>0
        $ 0.00</value>
        <webElementGuid>0023c2d4-c825-414c-a51d-caf9e5afc445</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Go to cart</value>
        <webElementGuid>0023c2d4-c825-414c-a51d-caf9e5afc445</webElementGuid>
    </webElementProperties>
</WebElementEntity>