<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1a42df36-4fc4-4bd6-b2f4-cab96c3dfe15</elementGuidId>
    <imagePath></imagePath>
    <name>link_ProductDetail</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/main[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[2]/div[1]/div[1]/span[1]/div[1]/div[1]/div[6]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'//tka.tiki.vn/pixel/pixel?data=_8Wzk6CQ_Xukd_a12jyFLDDX8-j9QcPPJ0zqu5heqzCYB9OUMYwM-f4h1l1WPJa8-RlrFtK_dkrkQRQYzoGaifrp30szPqa1iBivj_s-iUK8PjDgsR3OrZZyYNv8J66k7XVzKN4lfkN0b3B3lfMmory6oPbDOZkBPxKxsWTNdFELZaJwjfilZ6NNoJy_C-uOOuMSZqoFOLnKbNHIiaXX-eMuFbtvczQ8utsWqoCNpoE68KOVUMVpNE9DN38dnluUlAYZF-2Kxo6kGiBgBaI_XN2oSdTM2tEGr0M2ktE9FfkxPSpqxnqha7XxzpnCMRhNzbOY0mOrWQ_9TMDMYwEm65HG2oF979k-KNH0Aan-rUwprTeGC-By5aTMN-YD6ZU1_GvxBiFtDmfRdr9yru-nSAoK8qV4UA1ENbvyxczABmOA63Lv5d0Osg8pzdmL1GiK0Qqv8arJ4RfRuIOXm7W7FymDkDfk-GcNUCSCF-kor0Uu6aL-evllEOXoEygDTt4FKU-1Ud01PgqzmyVCSLCS0mzy5aJ6h_SL93m8yRHOQSd9EpN5mlOI3hIQ54-K_JUEKmgzhNS5QzdG0QsRpQKadgqcOtHYBjIJSBzcZseHCD6pyY_nOmPIrhaQCas0re5CdadEAVmu1NUO9O2T7WCx0AgK5nO3rT_NqH1NRGxISPFeCJDdz6EcvZAbF5hDHgM9kohUWsy2g2zfnAMJwUCG-KItQGrJ9T8q0jH0xidjDfZKp7zzgfJnvXsKtiHp7y8alZb1z6APbtElZo9eKSuep_Bewphn4AcSdRv-Z3nbYIzdsyPU41bLL5S00892aAbaXq0ctfj4R5EKRa5L7ZfgKxAZgb6EkAx0btB8hsDgCbhfsj4WtU2QqMKDibcttIz51A8cmZuMcsfR10bZoKYtoFUm1svEBQGExZ-DTf3oUqwk8JWF9XaKeBsp-LXgEqxU4rYsdTPJSgAZQCcxj13zjmsorKe-s-Gec_jTo3BOFUxyrMQpUjW94-13i5Uccthxrv1mPDvJ-t0ZIlmeZgiTT66XkGmEwXo-gQ&amp;pos=6&amp;reqid=XbmI0quOzn&amp;type=CLICK') and equals(@text,'AD
            
            Truyện cổ tích Ăn Khế Trả Vàng
            33.000₫')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:has-text="ADTruyện cổ tích Ăn Khế Trả V"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>//tka.tiki.vn/pixel/pixel?data=_8Wzk6CQ_Xukd_a12jyFLDDX8-j9QcPPJ0zqu5heqzCYB9OUMYwM-f4h1l1WPJa8-RlrFtK_dkrkQRQYzoGaifrp30szPqa1iBivj_s-iUK8PjDgsR3OrZZyYNv8J66k7XVzKN4lfkN0b3B3lfMmory6oPbDOZkBPxKxsWTNdFELZaJwjfilZ6NNoJy_C-uOOuMSZqoFOLnKbNHIiaXX-eMuFbtvczQ8utsWqoCNpoE68KOVUMVpNE9DN38dnluUlAYZF-2Kxo6kGiBgBaI_XN2oSdTM2tEGr0M2ktE9FfkxPSpqxnqha7XxzpnCMRhNzbOY0mOrWQ_9TMDMYwEm65HG2oF979k-KNH0Aan-rUwprTeGC-By5aTMN-YD6ZU1_GvxBiFtDmfRdr9yru-nSAoK8qV4UA1ENbvyxczABmOA63Lv5d0Osg8pzdmL1GiK0Qqv8arJ4RfRuIOXm7W7FymDkDfk-GcNUCSCF-kor0Uu6aL-evllEOXoEygDTt4FKU-1Ud01PgqzmyVCSLCS0mzy5aJ6h_SL93m8yRHOQSd9EpN5mlOI3hIQ54-K_JUEKmgzhNS5QzdG0QsRpQKadgqcOtHYBjIJSBzcZseHCD6pyY_nOmPIrhaQCas0re5CdadEAVmu1NUO9O2T7WCx0AgK5nO3rT_NqH1NRGxISPFeCJDdz6EcvZAbF5hDHgM9kohUWsy2g2zfnAMJwUCG-KItQGrJ9T8q0jH0xidjDfZKp7zzgfJnvXsKtiHp7y8alZb1z6APbtElZo9eKSuep_Bewphn4AcSdRv-Z3nbYIzdsyPU41bLL5S00892aAbaXq0ctfj4R5EKRa5L7ZfgKxAZgb6EkAx0btB8hsDgCbhfsj4WtU2QqMKDibcttIz51A8cmZuMcsfR10bZoKYtoFUm1svEBQGExZ-DTf3oUqwk8JWF9XaKeBsp-LXgEqxU4rYsdTPJSgAZQCcxj13zjmsorKe-s-Gec_jTo3BOFUxyrMQpUjW94-13i5Uccthxrv1mPDvJ-t0ZIlmeZgiTT66XkGmEwXo-gQ&amp;pos=6&amp;reqid=XbmI0quOzn&amp;type=CLICK</value>
        <webElementGuid>4b7de11f-dbb2-4de0-ada8-6c1dd550e181</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>AD
        
        Truyện cổ tích Ăn Khế Trả Vàng
        33.000₫</value>
        <webElementGuid>4b7de11f-dbb2-4de0-ada8-6c1dd550e181</webElementGuid>
    </webElementProperties>
</WebElementEntity>