<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c0773833-01b0-4344-a54a-c6216ade4dea</elementGuidId>
    <imagePath></imagePath>
    <name>button_PlaceOrder</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/main[1]/div[1]/div[2]/div[5]/div[7]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Đặt hàng')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Đặt hàng"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Đặt hàng</value>
        <webElementGuid>4b7de11f-dbb2-4de0-ada8-6c1dd550e181</webElementGuid>
    </webElementProperties>
</WebElementEntity>